### ISSUE TITLE
Libretto is vmware (govmomi) is out of date

### ISSUE THREAD

**Issue by sjpotter** [apcera/libretto#113]
this is a more complicated fix, as govmomi now requires go 1.7 which requires a lot of changes in libretto itself (at least in the vmware go, to use "contet")

**Comment by avnish30jn** [comment]
I have done the changes and created a PR for the same.

[https://github.com/apcera/libretto/pull/114](url)

**Comment by y0ssar1an** [comment]
Fixed in #120.
