### ISSUE TITLE
Cannot install library

### ISSUE THREAD

**Issue by agforte** [apcera/libretto#129]
When running `go get -u github.com/apcera/libretto/...` I get the following error:
```
package egoscale: unrecognized import path "egoscale" (import path does not begin with hostname)
```

I am using golang v1.8

Thanks.

**Comment by y0ssar1an** [comment]
Using the nonrecursive `go get` should work just fine. All the dependencies are in `vendor/`, so you should be good 😄
```sh
go get -u github.com/apcera/libretto
```

**Comment by y0ssar1an** [comment]
I just realized the recursive `go get` command was coming from our README. Sorry about that! That was our mistake. I've updated the instructions in #130.

**Comment by agforte** [comment]
Great. Thanks.
