### ISSUE TITLE
SSHClient.Disconnect() blocks if called multiple times.

### ISSUE THREAD

**Issue by devoid** [apcera/libretto#46]
Calls to `client.Disconnect()` after the first one will block indefinitely since the only reader, `keepAlive()`, returns after the first call. The channel could instead be safely closed if you implemented the function this way:

```
func (c *SSHClient) Disconnect() {
    select {
    case: <-c.close:
    default:
        close(c.close)
    }
}
```
And then altering some call under Connect to make a new channel if you are reusing the client later.
Hopefully this doesn't significantly change the library behavior.

I ran into the problem because `aws.VM.GetSSH(ssh.Options{})` makes a call to `client.WaitForSSH()` which calls disconnect internally before returning. I don't agree with the semantics of that behavior... you wait for a connection but then you immediately tear it down? But changing that would probably have a greater API impact as the callers of each function would then be responsible for calling `Disconnect()`.

**Comment by zquestz** [comment]
Thanks for the report. We will look into this a bit more closely in the next few days.

**Comment by zquestz** [comment]
Finally got around to this. Sorry for the delay. PR is up.
