### ISSUE TITLE
SSHClient not thread safe

### ISSUE THREAD

**Issue by johnSchnake** [apcera/libretto#47]
The SSHClient has a pointer to SSH credentials.  However, when a VM creates a client via `GetSSH` the most probable thing that it does is just give it a pointer to a shared object.  This means that the setters and getters for those credential objects are no longer thread safe.

I see a few options:
 1. Add a shared mutex; all of the clients would have to get this mutex so they can coordinate.
 2. Copy credentials each time a client is made rather than having a pointer.  This would have the side effect that if you spawned multiple clients from the VM at different times they may have different credentials internally (from each other).

I'm not sure if there would be some other way to handle this? (2) seems like it should be the right choice; not sure if there are other side effects of this behavior though.  Even though this wouldn't change the Client interface it would be changing the SSHClient struct, so it would be a breaking change.

@y0ssar1an @lilirui @zquestz @variadico

**Comment by y0ssar1an** [comment]
```go
// SSHClient provides details for the SSH connection.
type SSHClient struct {
	Creds   *Credentials
	IP      net.IP
	Port    int
	Options Options

	cryptoClient *cssh.Client
	close        chan bool
}
```
Could we solve this problem by changing `Credentials` to a non-pointer? Then every `SSHClient` would get a copy of the `ssh.Credentials` from the `VM`.

**Comment by johnSchnake** [comment]
That was option 2 that I listed.  It changes the type but not the interface.  Could be breaking for users who either made a type assertion and used the Creds directly or if they were using one client to change the VM's credentials, which were then later expected to reflect that change.

**Comment by y0ssar1an** [comment]
I concur that 2 is the way to go. The risk of breakages seems low to me, but I could be wrong. If someone is mutating the VM object through the SSH client, that just seems wrong to me, but people might actually be doing that.

I'd support incrementing the major version number to 1.X.X to be clear about the risk.

**Comment by johnSchnake** [comment]
I hadn't realized we were still in v0; the point of which is to allow breaking changes more frequently.  That being the case I think its OK to do this w/o more than minor version bump to v.0.10.0. I'd like others opinion on that too though.

**Comment by mbhinder** [comment]
Unfortunately, the `Credentials` struct does not have getters and setters and just has exported fields so a mutex won't automatically solve the problem (I don't think John said it would, just clarifying what he said). 

Personally, I don't think this is such a problem. Access to shared memory inherently isn't thread safe, IMO the caller should take care of wrapping behavior in a mutex. I'm also not against adding one for convenience to the VM struct.

**Comment by y0ssar1an** [comment]
Remember when I thought it was crazy to mutate the VM credentials through the SSH client? Well, that's what we're doing in `apcera-setup`. It's the reason why `Creds` is a pointer. There's no way to change the SSH creds through a `libretto.VirtualMachine` interface type, except through the client returned by the type's `GetSSH()` method.

Solution 1 is looking more attractive.
