### ISSUE TITLE
question: Mac hardware

### ISSUE THREAD

**Issue by joeblew99** [apcera/libretto#81]
i need to run code on actual Mac hardware. Mostly to do with some custom build stuff with xcode.
I dont want to use travis etc, because this is much more complicated than just CI.

So, does anyone know if any of the providers supported offer booting virtual Macs ?

**Comment by mbhinder** [comment]
I believe it will work on Virtualbox on Apple labelled hardware and it might be technically possible on non Apple hardware as well by modifying the hypervisor but against Apple's TOS.

**Comment by joeblew99** [comment]
thanks.

i will try virtualBox on OSX host...
